In [5]:

import pandas as pd

In [ ]:
url1 ="All_train_data.csv"
dataset1 = pd.read_csv(url1)

In [ ]:

dataset1.head()

                                               input  labels
0    I am reading score of Mahler is Symphony No . .       0
1  I am not interested in cars or electric applia...       1
2         This is my homework for my English class .       0
3  In comparison , Canada is catches increased an...       0
4  Fortunately , my older sister is friend is a d...       1

In [ ]:
 
dataset2 = pd.read_csv("filename.csv",index_col=0)
dataset2.head()

,uid,sentence1,sentence2,label,tree
0,1,A person on a horse jumps over a broken down a...,"A person is at a diner, ordering an omelette.",Contradiction,(9 (1 (14 (14 (41 a/a) (32 person/person)) (10...
1,10000,A dog running in the grass.,Outside there is an animal on the move.,Entailment,(9 (4 (4 (35 /outside) (49 /there)) (49 /is)) ...
2,100143,Two dogs play on the wooden floor inside.,the dogs have a toy ball,Neutral,(9 (1 (14 (60 two/the) (65 dogs/dogs)) (31 (31...
3,100177,A woman in overalls is painting a landscape on...,There is a women painting,Entailment,(9 (4 (89 a/there) (43 /is)) (9 (1 (14 (14 (41...
4,1002,Small laughing child with blond-hair sitting a...,A child is throwing a tantrum.,Contradiction,(9 (1 (14 (14 (94 small/) (24 (68 laughing/a) ...

In [ ]:
print("dataset1:")
display(dataset1.head())
print("dataset2:")
display(dataset2.head())

dataset1:

                                               input  labels
0    I am reading score of Mahler is Symphony No . .       0
1  I am not interested in cars or electric applia...       1
2         This is my homework for my English class .       0
3  In comparison , Canada is catches increased an...       0
4  Fortunately , my older sister is friend is a d...       1

dataset2:

,uid,sentence1,sentence2,label,tree
0,1,A person on a horse jumps over a broken down a...,"A person is at a diner, ordering an omelette.",Contradiction,(9 (1 (14 (14 (41 a/a) (32 person/person)) (10...
1,10000,A dog running in the grass.,Outside there is an animal on the move.,Entailment,(9 (4 (4 (35 /outside) (49 /there)) (49 /is)) ...
2,100143,Two dogs play on the wooden floor inside.,the dogs have a toy ball,Neutral,(9 (1 (14 (60 two/the) (65 dogs/dogs)) (31 (31...
3,100177,A woman in overalls is painting a landscape on...,There is a women painting,Entailment,(9 (4 (89 a/there) (43 /is)) (9 (1 (14 (14 (41...
4,1002,Small laughing child with blond-hair sitting a...,A child is throwing a tantrum.,Contradiction,(9 (1 (14 (14 (94 small/) (24 (68 laughing/a) ...

In [ ]:

display(dataset1.head())
dataset1.rename(columns = {'labels':'output',}, inplace = True)
#dataset1.drop(columns=['labels'],inplace=True)
display(dataset1.head())

                                               input  labels
0    I am reading score of Mahler is Symphony No . .       0
1  I am not interested in cars or electric applia...       1
2         This is my homework for my English class .       0
3  In comparison , Canada is catches increased an...       0
4  Fortunately , my older sister is friend is a d...       1

                                               input  output
0    I am reading score of Mahler is Symphony No . .       0
1  I am not interested in cars or electric applia...       1
2         This is my homework for my English class .       0
3  In comparison , Canada is catches increased an...       0
4  Fortunately , my older sister is friend is a d...       1

In [ ]:
display(dataset2.head())
dataset2.drop(columns=['label','tree','uid'], inplace=True)
display(dataset2.head())

,uid,sentence1,sentence2,label,tree
0,1,A person on a horse jumps over a broken down a...,"A person is at a diner, ordering an omelette.",Contradiction,(9 (1 (14 (14 (41 a/a) (32 person/person)) (10...
1,10000,A dog running in the grass.,Outside there is an animal on the move.,Entailment,(9 (4 (4 (35 /outside) (49 /there)) (49 /is)) ...
2,100143,Two dogs play on the wooden floor inside.,the dogs have a toy ball,Neutral,(9 (1 (14 (60 two/the) (65 dogs/dogs)) (31 (31...
3,100177,A woman in overalls is painting a landscape on...,There is a women painting,Entailment,(9 (4 (89 a/there) (43 /is)) (9 (1 (14 (14 (41...
4,1002,Small laughing child with blond-hair sitting a...,A child is throwing a tantrum.,Contradiction,(9 (1 (14 (14 (94 small/) (24 (68 laughing/a) ...

,sentence1,sentence2
0,A person on a horse jumps over a broken down a...,"A person is at a diner, ordering an omelette."
1,A dog running in the grass.,Outside there is an animal on the move.
2,Two dogs play on the wooden floor inside.,the dogs have a toy ball
3,A woman in overalls is painting a landscape on...,There is a women painting
4,Small laughing child with blond-hair sitting a...,A child is throwing a tantrum.

In [ ]:
dataset2.rename(columns = {'sentence1':'input','sentence2':'output'}, inplace = True)
dataset2.head()
dataset2.tail()

,input,output
16375,three people play soccer in the sand.,A sport is being played.
16376,A couple in old fashioned clothes sitting at a...,A couple is sitting at a table.
16377,A baby in a white and light purple outfit crying.,A baby is crying.
16378,A man shoots a gun that emits a bright light.,A man shoots a gun.
16379,Three little girls are sitting on a purple ben...,Three children are being silly.

In [ ]:

dataset3 = pd.read_csv("pdf.csv",index_col=0)

In [ ]:
dataset3.head()

,Original,Edited
0,Condensation Robot-assisted laparoscopic techn...,Condensation Robot-assisted laparoscopic techn...
1,Short titles Robot-assisted laparoscopic techn...,Short titles Robot-assisted laparoscopic techn...
2,The advantages of RAL were evaluated through t...,The advantages of RAL were evaluated through t...
3,Study design: Three electronic databases (PubM...,Study design: Three electronic databases (PubM...
4,All retrospective studies documenting a compar...,All retrospective studies documenting a compar...

In [ ]:
dataset3.rename(columns = {'Edited':'output','Original':'input'}, inplace = True)
#dataset1.drop(columns=['labels'],inplace=True)
display(dataset3.head())

,input,output
0,Condensation Robot-assisted laparoscopic techn...,Condensation Robot-assisted laparoscopic techn...
1,Short titles Robot-assisted laparoscopic techn...,Short titles Robot-assisted laparoscopic techn...
2,The advantages of RAL were evaluated through t...,The advantages of RAL were evaluated through t...
3,Study design: Three electronic databases (PubM...,Study design: Three electronic databases (PubM...
4,All retrospective studies documenting a compar...,All retrospective studies documenting a compar...

In [ ]:
display(dataset1.shape,dataset2.shape,dataset3.shape)

(29998, 2)

(16380, 2)

(1145, 2)

In [ ]:
merged_dataset = pd.concat([ dataset2, dataset3])
merged_dataset.shape

(17525, 2)

In [50]:
merged_dataset.tail()

,input,output
1140,Future research should focus on the impact of ...,Future research should focus on the impact of ...
1141,The four substitutional incentive policies in ...,The four substitutional incentive policies in ...
1142,"However, some region has more suitable incenti...","However, some region has more suitable incenti..."
1143,The impacts of these policies on EV adoption n...,The impacts of these policies on EV adoption n...
1144,33,33

In [54]:
# importing pandas
import pandas as pd
  
# merging two csv files
df = pd.concat(
    map(pd.read_csv, ['filename.csv', 'pdf.csv']), ignore_index=True)
print(df)

       Unnamed: 0       uid  \
0               0       1.0
1               1   10000.0
2               2  100143.0
3               3  100177.0
4               4    1002.0
...           ...       ...
17520        1140       NaN
17521        1141       NaN
17522        1142       NaN
17523        1143       NaN
17524        1144       NaN

                                               sentence1  \
0      A person on a horse jumps over a broken down a...
1                            A dog running in the grass.
2              Two dogs play on the wooden floor inside.
3      A woman in overalls is painting a landscape on...
4      Small laughing child with blond-hair sitting a...
...                                                  ...
17520                                                NaN
17521                                                NaN
17522                                                NaN
17523                                                NaN
17524                                                NaN

                                           sentence2          label  \
0      A person is at a diner, ordering an omelette.  Contradiction
1            Outside there is an animal on the move.     Entailment
2                           the dogs have a toy ball        Neutral
3                          There is a women painting     Entailment
4                     A child is throwing a tantrum.  Contradiction
...                                              ...            ...
17520                                            NaN            NaN
17521                                            NaN            NaN
17522                                            NaN            NaN
17523                                            NaN            NaN
17524                                            NaN            NaN

                                                    tree  \
0      (9 (1 (14 (14 (41 a/a) (32 person/person)) (10...
1      (9 (4 (4 (35 /outside) (49 /there)) (49 /is)) ...
2      (9 (1 (14 (60 two/the) (65 dogs/dogs)) (31 (31...
3      (9 (4 (89 a/there) (43 /is)) (9 (1 (14 (14 (41...
4      (9 (1 (14 (14 (94 small/) (24 (68 laughing/a) ...
...                                                  ...
17520                                                NaN
17521                                                NaN
17522                                                NaN
17523                                                NaN
17524                                                NaN

                                                Original  \
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
...                                                  ...
17520  Future research should focus on the impact of ...
17521  The four substitutional incentive policies in ...
17522  However, some region has more suitable incenti...
17523  The impacts of these policies on EV adoption n...
17524                                                 33

                                                  Edited
0                                                    NaN
1                                                    NaN
2                                                    NaN
3                                                    NaN
4                                                    NaN
...                                                  ...
17520  Future research should focus on the impact of ...
17521  The four substitutional incentive policies in ...
17522  However, some region has more suitable incenti...
17523  The impacts of these policies on EV adoption n...
17524                                                 33

[17525 rows x 8 columns]

In [49]:
df = pd.read_csv("combined-csv-files.csv",index_col=0)
df.head()

,uid,sentence1,sentence2,label,tree
0,1,A person on a horse jumps over a broken down a...,"A person is at a diner, ordering an omelette.",Contradiction,(9 (1 (14 (14 (41 a/a) (32 person/person)) (10...
1,10000,A dog running in the grass.,Outside there is an animal on the move.,Entailment,(9 (4 (4 (35 /outside) (49 /there)) (49 /is)) ...
2,100143,Two dogs play on the wooden floor inside.,the dogs have a toy ball,Neutral,(9 (1 (14 (60 two/the) (65 dogs/dogs)) (31 (31...
3,100177,A woman in overalls is painting a landscape on...,There is a women painting,Entailment,(9 (4 (89 a/there) (43 /is)) (9 (1 (14 (14 (41...
4,1002,Small laughing child with blond-hair sitting a...,A child is throwing a tantrum.,Contradiction,(9 (1 (14 (14 (94 small/) (24 (68 laughing/a) ...

In [50]:


df.drop(columns=['label','tree','uid'],inplace=True)
df.rename(columns = {'sentence1':'input','sentence2':'target'}, inplace = True)
display(df.head())

,input,target
0,A person on a horse jumps over a broken down a...,"A person is at a diner, ordering an omelette."
1,A dog running in the grass.,Outside there is an animal on the move.
2,Two dogs play on the wooden floor inside.,the dogs have a toy ball
3,A woman in overalls is painting a landscape on...,There is a women painting
4,Small laughing child with blond-hair sitting a...,A child is throwing a tantrum.

In [51]:
df['input'] = 'grammar: ' + df['input'].astype(str)
#df['input'].map('grammer{}'.format)
display(df.head())

,input,target
0,grammar: A person on a horse jumps over a brok...,"A person is at a diner, ordering an omelette."
1,grammar: A dog running in the grass.,Outside there is an animal on the move.
2,grammar: Two dogs play on the wooden floor ins...,the dogs have a toy ball
3,grammar: A woman in overalls is painting a lan...,There is a women painting
4,grammar: Small laughing child with blond-hair ...,A child is throwing a tantrum.

In [48]:
df.to_csv('final3.csv')

In [5]:
dataset3 = pd.read_csv("pdf.csv",index_col=0)

In [6]:
dataset3.rename(columns = {'Edited':'tar','Original':'input'}, inplace = True)
#dataset1.drop(columns=['labels'],inplace=True)
display(dataset3.head())

,input,output
0,Condensation Robot-assisted laparoscopic techn...,Condensation Robot-assisted laparoscopic techn...
1,Short titles Robot-assisted laparoscopic techn...,Short titles Robot-assisted laparoscopic techn...
2,The advantages of RAL were evaluated through t...,The advantages of RAL were evaluated through t...
3,Study design: Three electronic databases (PubM...,Study design: Three electronic databases (PubM...
4,All retrospective studies documenting a compar...,All retrospective studies documenting a compar...

In [7]:
dataset3['input'] = 'grammar: ' + dataset3['input'].astype(str)
#df['input'].map('grammer{}'.format)
display(dataset3.head())

,input,output
0,grammar: Condensation Robot-assisted laparosco...,Condensation Robot-assisted laparoscopic techn...
1,grammar: Short titles Robot-assisted laparosco...,Short titles Robot-assisted laparoscopic techn...
2,grammar: The advantages of RAL were evaluated ...,The advantages of RAL were evaluated through t...
3,grammar: Study design: Three electronic databa...,Study design: Three electronic databases (PubM...
4,grammar: All retrospective studies documenting...,All retrospective studies documenting a compar...

In [9]:
dataset3.to_csv('final_1.csv')

In [7]:
dt= pd.read_csv("train.csv",index_col=0)
dt.head(10)

                                                                                               target
input
grammar: So I think we can not live if old peop...  So I think we would not be alive if our ancest...
grammar: So I think we can not live if old peop...  So I think we could not live if older people d...
grammar: So I think we can not live if old peop...  So I think we can not live if old people could...
grammar: So I think we can not live if old peop...  So I think we can not live if old people can n...
grammar: For not use car .                                                  Not for use with a car .
grammar: For not use car .                                                   Do not use in the car .
grammar: For not use car .                                                         Car not for use .
grammar: For not use car .                                                     Can not use the car .
grammar: Here was no promise of morning except ...  Here was no promise of morning , except that w...
grammar: Here was no promise of morning except ...  Here , there was no promise of morning , excep...

In [8]:
dt.dropna(axis=1, inplace = True)
dt.head()

                                                                                               target
input
grammar: So I think we can not live if old peop...  So I think we would not be alive if our ancest...
grammar: So I think we can not live if old peop...  So I think we could not live if older people d...
grammar: So I think we can not live if old peop...  So I think we can not live if old people could...
grammar: So I think we can not live if old peop...  So I think we can not live if old people can n...
grammar: For not use car .                                                  Not for use with a car .

In [12]:
dt.shape

(3016, 1)

In [13]:
dt.isnull().any()

target    False
dtype: bool

In [16]:
df.to_csv('train1.csv')

In [17]:
pip install faker

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting faker
  Downloading Faker-16.6.1-py3-none-any.whl (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 19.7 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.8/dist-packages (from faker) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil>=2.4->faker) (1.15.0)
Installing collected packages: faker
Successfully installed faker-16.6.1

In [18]:
from faker import Faker
import pandas as pd
import numpy as np

In [19]:
fake = Faker()

In [23]:
for _ in range(100):
  x = fake.text()
  print(x ,"\n")

Mouth listen simple too letter rich. Sit upon own dog.

Coach rock people food mind fire. Rock also economic contain international all.
Machine raise career. Third hard bill operation animal.

Effort enter may news step take history. Member learn side I order president able.
Method understand with. Why speech investment bring piece course white bag.

Measure where stock security series prevent spring. The about bank future person indicate. Time personal candidate our.
Happen nor bad. Feel so half situation even.

Sense not take first. Set choice nothing chair still position scientist number. List big ask his life blue quite area.
Anyone laugh cut debate land. Success create this thousand push past us.

Out all interesting live this. Soon what provide quickly less ready receive.
General technology shoulder top. News various window company avoid result huge. Also many state should election appear.

Yourself process prove past require. Voice of building stand against together color. Population southern close himself art.

Fear season real learn subject shake focus. Art throw evidence radio military deal. Fall follow western. Open stop paper stand choice thus.

Consumer woman black mean. Once after quality attention American peace health art. Create main arrive.
Seat movement place south. Billion out may. Seven Republican address leg cut soldier baby.

Bit history book attorney financial kind. Sign avoid stuff hear money. Clear future act picture job.
Well knowledge light same before later you. Agent community result drive road final wife.

Mr work however game degree to everything decision. Sure fly red night stock discover once.
Their sense card sure civil certainly. There risk always. Consider actually subject pay market investment.

Today section really industry especially sometimes. Board important here learn film able history growth. Painting those bank plant for college ahead.

Something by major bad effect oil firm. Fly future high less since. Second throw social risk you.
Vote source close culture wrong. Throughout keep nearly.

Despite land new forget tough.
Successful far edge listen nearly size significant. Opportunity watch trial prevent pass air. Rather generation would travel.

Mrs store light. Simple would seek way summer.
Mother sound speak Congress sometimes speech level. Last lawyer admit out eight.

Agreement maybe sit rest. Relationship teacher power listen cause term.
Theory national community anything office tend. Lot just cover benefit shoulder process wrong exactly.

Staff out both use key around participant. Rather central concern concern human food rock.
Week author that point back local. International plant ahead. Sure poor watch smile wait drop physical.

Enjoy season it cost. Join culture about bill time. Watch soon traditional.

Of organization oil information step stop employee before. Reach law expect parent.
Possible throw money be season. Again however thought. End after generation first reality.

Meet space lay himself agency law leave political. Onto cell left friend not. Different provide brother sense kitchen.

Else for claim four pressure southern us foreign.
Receive then its board create shake much despite. Someone me blue character feeling into.

Day attention but.
Environmental final trade friend forget service wait. Father begin industry listen bit threat.

Remember money play quickly. Condition walk happy live toward.
Best small trade series. My cost certain federal take others day.

Question movement special. Two entire strategy detail use wrong others need. Tonight market trip visit require control work.

Outside fear position near. Appear forward attention enjoy six help year relationship.
Peace American nor several. Authority short everything bit quality small develop.

Fast sport imagine yard affect place. Back wall bad child. Their none play nice increase.
View door interview range hard Mrs. Happy reflect data black.

Least response after about hit able decade rich. Voice box garden me detail set.
Admit issue could make. Religious tell painting employee detail. Woman would avoid activity authority decision.

Bring difference sound situation.
Prove member win bill find development. Energy choice suggest stop skin.
Owner face work community war president with. Mr play under member social.

Brother those challenge walk research happen case. Price research event decade child accept unit. More again big top.

Worker skin series. Rather six third place.
Probably reach serious. Pm us court debate night. Able mention detail.
Thus oil gas pressure. Case report call student executive order walk.

National main theory something. Training scene amount owner power blue decision. Drive though tree scientist. Discussion together trial never.

Dream method design begin north. About full detail break face. Occur fish way green skill.
But happen possible blue.
Too break page effect main little. Group strategy lawyer part network say.

Space increase pay student pattern example. Reach benefit government open rule thank feel.

Material artist mention speech return. Safe girl least dog begin star.

Return standard figure head toward. Have available draw doctor.
Perform owner specific scene. Usually month where current staff head. National last author type doctor pay for.

Continue next miss reach. Past face in fund able. Whole necessary hotel attorney they model investment.

Administration power well. Name available join while truth PM suffer. Attention worker can off floor believe foot.

Year structure player structure than. Relationship on so once. Section line team consider.
Hard when loss various rock probably month.

Wonder than manager attack get defense new truth. Senior more specific turn.
Sort news see place car. Song science ahead score prepare this throughout feeling. Method nature yet site hospital.

Second happy short. Carry edge send easy campaign friend next meeting. Between can simply our item.
Lawyer positive television green outside.

Man author sing foreign. Carry computer interesting response.
Half fund it police how usually likely attack.

Box remember economic fine majority example fight face. Message control force affect.
Forward two green many fight. Method develop run later listen. Night down very growth value our.

As adult product result consumer number. To none pick pay simply development. Threat else hope process result.
Huge move huge kind. Fund family traditional share high.

Morning full happen which offer like paper. Talk task state them opportunity current buy.
Design yourself lead somebody weight finish no man. Make analysis ask myself discuss notice herself.

Play public not. Include him close never. Mention thousand choice soldier require fish student.
Hair system left detail myself. Section indeed admit voice. Nature away certain actually she so drug.

Writer not wonder rock list seven. Paper still story nor region role. Often discover customer new.
Determine blood approach major. Help seem bit wrong city.

Push set case base raise never stand quality. Our ago season serious discover various.
Tell serious deal fly. Under recent south computer room nor network.

General ball want lot. Admit policy company strategy. Even do nothing successful. Member somebody interview.

Recent why bad us media husband. Clearly event have benefit.
Hotel development American people area rock group. Leg data however art. Natural special at interest Mrs direction.

Mother but employee big item none. Want herself television rise list many short.
Small country need.

Want each career by no answer. Can subject avoid we down. Right cultural determine development mother.

Single happen team discover big. Easy reduce hope hand authority may.
Entire discover every huge leave church middle challenge. Now Congress help.
Receive southern allow argue. Gun security first.

Thing part may social state former watch read. Coach visit up. Threat physical back I us black production.
Share over number clear factor notice similar think. Accept drive family call say.

Hundred style newspaper bill to. Project interesting box forget company case.
Few message south economy however tree process. Anyone own so affect.
Seek mission picture gas rather.

Guess guy expert physical current. Kid before edge. Deal always white culture since risk give beyond.
Adult source nothing environmental much us. Grow write onto knowledge century yeah.

Hard manage together into structure must. Evidence meet whatever rule send.
End a might someone evidence. Least kind modern leg top career second thus. Ball time head.

Meeting open every skin senior close. Call professional allow ability.
Idea nation poor bar. Avoid peace pressure baby themselves candidate produce.

According rock learn I. Need ground table effort gas.
Carry piece campaign so media Congress. Use base realize answer hour job south. Many woman field important.

Tell local present stage easy. Author expert ask rate other. Nature born really say once.

What serious our month argue they argue. Suggest pretty voice degree trouble.
Stand arrive tend sit hope material. Position language long foot night week recognize computer.

Play present fast control. With around entire. Interview enough discover kid well. Agree police not put.
Factor police speech citizen. Particular but general site hand whom.

Music tonight listen. Third trip reveal magazine. Step father guy garden cultural media. Born present poor receive seek.

Former here democratic grow. Term interview cold out laugh hope hotel.
Accept computer present value teach. Rather tree doctor Mrs social.

Speak something nothing worker like remain. Scene ask professional magazine. Whether government run employee training.

Spend foreign wrong face. Art huge assume others standard material player during. Method soon name stage yes kid should.

Conference room clear subject. Nothing know fund thing involve instead.
Low large technology anything tell least.
Never money her. Cost into heart respond left.

Respond event how space director any individual challenge. Operation knowledge science wind role. Subject vote store two now trouble thing.

Away first piece board lot chance film. Sort despite half only fight nice. From item left almost. Method poor language deal section.
Much ago occur because crime statement. Mr without lawyer series.

Eat TV public close activity between.
Rule something produce reality allow score. Page organization difference me particularly. Business environmental deep probably soon action.

For small trouble raise under relationship argue. Add follow lawyer wind I dog letter.
Cost remember member sister his detail allow tell. At rock break population during could during.

Example us middle range near. Price so public beyond ahead recently order. Argue foreign risk agency week writer rest.
Order reason southern father hear. Fine task development deal dark show.

Rather name civil candidate sister. Require week agency health black claim free. Line hand machine common picture behind.

Be trial out into song. Summer town relationship wonder fish. International indicate move same his on west.
Never four happy letter. Myself teacher less although continue build between.

Arm include model own. Senior then might go describe. Him tax student significant able.

Capital character manager central add writer.
Other listen already who event myself board. Sign particularly run recently. Available summer hold near into hair.

Wish purpose control parent pay yet leader. Consumer ground detail friend yourself yourself teach. Ever it here play back knowledge. Line word low candidate because.
Child herself hot grow energy.

Reflect cover with heavy yes join field. Heart condition trouble job box himself suffer. Believe nor big fire.
Ok glass far piece whatever pull any. In tax reach.

Minute step magazine market. Determine president however spring. Power address official cost nation prepare.
Road onto manager. Miss full behavior station might we.

Move walk owner car maybe. Agree wish thing thank keep sell soldier Republican. Power available control heart once probably kid.

Size hold finally five tax. Put society military others show question. Finally early company.
Cell view decade nothing. Edge receive piece nice lead picture. Short price responsibility defense near.

Author beyond current garden. Assume top allow.
I natural majority beat gun. May hear decade police movement without though. Nearly would else himself.

Me party strategy reveal bank human. Entire you stock yet opportunity certain class get.
Day argue out attack mouth. In or one more.

Very term would seat player eat for. Huge something return say director.
Most experience direction modern fight foreign too. Hold heart operation take provide. Camera will four.

Cultural analysis should away. Responsibility much significant article field fund administration.
Sell major need truth walk. Account high only long. Chance chair bit simply they technology nice.

Worry teach increase. Analysis day this stock than especially. Particular another agree experience common of research.

Later check method challenge. Science clear material according candidate professional guess operation. Series family eat join learn set. State responsibility page authority fight.

Since born crime card probably. Determine cause cause response across.
Can book cup the feeling turn week. See professional certain civil might painting nearly.

Threat professional yes choose research practice wear. Possible meeting both. Skin newspaper recognize painting.

Shake on born decade race. Boy nothing career land.
Security response address. Capital sure huge sea. Enough every those make stop top measure.

General evidence for tell kind experience former only. Appear oil weight. Few environment including claim he nearly he.

Say last article. Method draw your also almost hand identify.
Continue single sort system. Structure board here chance job yeah color doctor.
Mrs its green sort. Allow war effect truth all bar do.

Station improve easy old check avoid measure. Pay model take them cost. Decision prepare force camera thing.
Seat pressure inside affect concern no. Anything box cover him job beat it.

Week some current city little speech clearly. Down some look cell low language offer down.
Go bar hundred movement.
Air true move kind ask nation. Source bed officer when try.

Develop deal write firm. Deep management continue large within total American enjoy. See brother student join.

Safe positive eye decision else. Generation sit space collection away case property. Order beyond style stuff bit significant rate.

Value it anything away doctor. Simply form result manage local.
Probably partner tell manage still event. Former song through wind air day. Affect building person seem perform.

Throughout air student forward almost.
Of decide only indeed eye center difference. Serious exist memory trade there each as. Dog use spring drug.

Sometimes animal black ball adult. Security material wear.
Common recognize there development sort. Hot heavy or another air. Argue clearly window once.

Card positive husband add. Week state threat able.
Fund threat here several several school campaign.

Environment information very assume back drive.
Create together now collection no human some. Arm continue actually indeed one bag. Water tough against economy notice garden gas tree.

In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("final_1.csv",index_col=0)
df.head()

                                                                                               output
input
grammar: Condensation Robot-assisted laparoscop...  Condensation Robot-assisted laparoscopic techn...
grammar: Short titles Robot-assisted laparoscop...  Short titles Robot-assisted laparoscopic techn...
grammar: The advantages of RAL were evaluated t...  The advantages of RAL were evaluated through t...
grammar: Study design: Three electronic databas...  Study design: Three electronic databases (PubM...
grammar: All retrospective studies documenting ...  All retrospective studies documenting a compar...

In [5]:
df.dropna(axis=1, inplace = True)
df.head()

                                                                                               output
input
grammar: Condensation Robot-assisted laparoscop...  Condensation Robot-assisted laparoscopic techn...
grammar: Short titles Robot-assisted laparoscop...  Short titles Robot-assisted laparoscopic techn...
grammar: The advantages of RAL were evaluated t...  The advantages of RAL were evaluated through t...
grammar: Study design: Three electronic databas...  Study design: Three electronic databases (PubM...
grammar: All retrospective studies documenting ...  All retrospective studies documenting a compar...

In [6]:
df.to_csv("final.csv")